sonar.projectKey=ares_safety
sonar.projectName=Ares Safety
sonar.projectVersion=1.0

sonar.sources=app/src/main/java

sonar.host.url=http://localhost:9000

sonar.token=squ_08e888ef7051e7741ed653909b6318215f304c07